### PR TITLE
Issue 184 comment email

### PR DESCRIPTION
**Pull request by petrus7**
Swtich to send email notifications only for resource owner

https://github.com/geosolutions-it/unesco-ihp/issues/184

### CODE REVIEW

**Comment by petrus7** [comment]
1. cite from the issue:
"they ask how much it would take to implement a configuration option "
2. Fixed

**Comment by petrus7** [comment]
@giohappy this was fixed long time ago is it ready to make PR against upstream?

**Comment by giohappy** [comment]
I've just tested this (after merging master) but something is not working as expected:

1. As a casual user I've added a comment to a document owned by user1
2. An email was sent to user1 recipient BUT I can't see any message in the user1 inbox
3. No email nor message was sento to administratiors

Can you replicate this?

**Comment by petrus7** [comment]
@giohappy 
1) Code there was never intended to send Geonode message
2) At the beginning notification was sent to all users which subscribe this type of notification. this task was about narrowing it only to the owner. Admins and Managers are not taken into consideration by my code

**Comment by giohappy** [comment]
1. Right, forget my comment about messages
2. Restrict to owner, but admins should receive them if they set the notification on.

**Comment by petrus7** [comment]
Admins are added to notifications

**Comment by petrus7** [comment]
close cuz of this: https://github.com/GeoNode/geonode/pull/6002

**Pull request closed without merging**
