### PR TITLE
workaround for hiding date field description

### PR DESCRIPTION
**Pull request by petrus7**
workaround to force hide mandatory description on date input field

https://github.com/geosolutions-it/unesco-ihp/issues/191

### CODE REVIEW

**Comment by giohappy** [comment]
@petrus7 why are you doing it on geonode repo instead of UNESCO?

**Comment by giohappy** [comment]
I'm not sure what you're hiding here, can you give me more infos to test it?

**Comment by petrus7** [comment]
@giohappy This is done for geonode because issue is present also there. Code is lucky enough not to fall into it. In general, fields which are under mandatory tab and are empty they display prompt: _* Field declared mandatory...._ This logic is written in _metadata_form_js.html_ In general this prompt is not properly styled and breaks when attached to small input. To be honest i dont understand logic in this file, thats why i force to hide prompt in case of date fields and that's why I find call this fix. That condition hide prompts here:

image

**Comment by giohappy** [comment]
If I'm not wrong they're not mandatory on GeoNode but they are for UNESCO. 
If they're mandatory a prompt is required to let the user know that the fields must be filled.

Hiding the prompt is not a solution in this case. I don't want to send workarounds (that, in this case, will break a functionality if the field is mandatory).

**Comment by petrus7** [comment]
I understand, in general this view requires deep refactor, there are more things which are broken. For example:
image

the first red square is never getting green 

Besides logic is connected to HTML structure, it is problematic to make it universal for upstream and other repos

**Comment by giohappy** [comment]
If a generic fix is too complex now please let's move the fix /workaround to UNESCO custom template, not here. But keep in mind that, if those fields are marked as mandatory, we need a prompt for the user in case they're not filled

**Pull request closed without merging**
