### PR TITLE
remove html tags before metadata xml creation

### PR DESCRIPTION
**Pull request by petrus7**
simply change to metadata template file

### CODE REVIEW

**Review by afabiani — CHANGES_REQUESTED** [review]
More or less good, even if the regex used to strip html tags seems to me a bit too much intrusive. I'll give it a try.

@petrus7 can you please add 1 or 2 small test cases? That should be relatively easy for this kind of change. Thanks.

**Comment by petrus7** [comment]
@afabiani done

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
@giohappy @petrus7 I'm going to create an issue and a PR against GeoNode core for this one

**Comment by giohappy** [comment]
ok @afabiani

**Pull request closed without merging**
